config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :students
  resources :courses
  root "pages#home"
  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"
  post 'enroll', to: "rolls#create"
  delete 'unenroll', to: "rolls#destroy"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < ApplicationRecord
  has_many :student_courses
  has_many :students, through: :student_courses
end

app/models/student.rb
class Student < ApplicationRecord
  has_many :student_courses
  validates :username,uniqueness: {case_sensitive: false}
  has_many :courses, through: :student_courses
end

app/models/student_course.rb
class StudentCourse < ApplicationRecord
  belongs_to :student
  belongs_to :course
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :logged_in?, :require_student
  def current_student
    @current_student ||= Student.find(session[:student_id]) if session[:student_id]
  end
  def logged_in?
    !!current_student
  end
  def require_student
    if !logged_in?
      flash[:red] = "you must be logged in to perform that task."
      redirect_to login_path
    end
  end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: [:show, :update,:destroy,:edit]
  before_action :require_student
  def home
  end
  
  def index
    @courses = Course.all
  end
  def new
    @course = Course.new
  end
  
  def create
      @course = Course.new(course_params)
      if @course.save
        flash[:success] ="The course is created"
        redirect_to courses_path
      else
        render 'new'
      end
  end
  
  def show
  end
  
  def edit
    
  end
  def update
    @course.update(course_params)
    redirect_to courses_path
  end
  
  def destroy
    @course.destroy
    flash[:success] ="The course #{@course.name} is deleted."
    redirect_to courses_path
  end
  
  private 
  def set_course
    @course = Course.find(params[:id])
  end
  
  def course_params
    params.require(:course).permit(:name, :description,:job_title, :category_id)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def home
	end
end

app/controllers/rolls_controller.rb
class RollsController < ApplicationController
  before_action :require_student
  
  def create    
    @student_course = StudentCourse.new
    @student_course.student_id = session[:student_id]
    @student_course.course_id = params[:course_id]
   if @student_course.save
     flash[:success]="You are enrolled to course"
   else
     flash[:error]="Enroll failed"
   end
    redirect_to student_path(Student.find(session[:student_id]))
  end
  
  def destroy
    course = Course.find(params[:course_id])
    @student_course = StudentCourse.find_by(student_id: current_student.id, course_id: course.id)
      if  @student_course.destroy
        flash[:success]="You are UnEnroll to course #{course.name}"
      else
        flash[:error]="UnEnroll failed "
      end
    redirect_to student_path(current_student)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :logged_in_already, only: [:new,:create]
  def new
    
  end
  def create
    student = Student.find_by(username: params[:session][:username])
      if student
        flash[:success] = "you are successfully log in."
        session[:student_id] = student.id
         if student.username.downcase == 'admin'
           session[:admin] = 'Y'
         end
        redirect_to courses_path
      else
        session[:admin] = nil
        flash[:error] = "login failed."
        redirect_to login_path
      end
  end
  
  def destroy
    session[:student_id] = nil
    session[:admin] = nil
    flash[:success] = "you are successfully log out."
    redirect_to login_path
  end
  
  private
  def logged_in_already
    if logged_in?
      flash[:success] ="You are already login."
      redirect_to courses_path
    end
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :require_student, except: [:new,:create]
  before_action :current_student, except: [:new,:create]
  before_action :set_student, only: [:edit,:destroy,:show]
  def home
  end
  def index
    @students = Student.all
  end
  
  def new
    @student=Student.new
  end
  
  def create
    @student = Student.new(student_params)
    if @student.save
      flash[:success]="Your account is successfully created."
      redirect_to login_path
    else
      flash[:error]="Your account creation failed."
      render 'new'
      
    end
  end
  
  def update
    if current_student.update(student_params)
      flash[:success]="Your account is successfully updated."
      redirect_to student_path(current_student)
    else
      flash[:error]="Your account updating failed."
      render 'edit'
    end
  end
  
  def edit
    
  end
  
  def show
      @my_courses = @student.courses 
  end
  
  def destroy
    if @student == current_student
      @student.destroy
      flash[:error]="Your account is deleted."
      session[:student_id]=nil
      redirect_to login_path
    else
      @student.destroy
      flash[:error]="This student account is deleted."
      redirect_to students_path
    end
    
  end
  
  private 
  def set_student
    @student = Student.find(params[:id])
  end
  def student_params
    params.require(:student).permit(:username,:firstname,:lastname,:email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/courses/_course.html.erb
<div class="four wide column">
<div class="ui cards">
	<div class="card">
	    <div class="content">
	      <div class="header">
	        <%= course.name%>
	        <% if controller.controller_name=="courses" && controller.action_name=="index" && session[:admin] && session[:admin].downcase=="y" %>
	        	<%= link_to '<i class=" trash icon right floated"></i>'.html_safe, course_path(course), method: :delete, data: {confirm: "Are you sure to remove this course?"}%>
	        	<%= link_to '<i class=" edit icon right floated"></i>'.html_safe, edit_course_path(course)%>
	        <% end %>
	      </div>
	      <!---<div class="meta">
	        <%= course.name%>
	      </div>--->
	      <div class="description">
	         <%= course.description%>
	         <p><%= pluralize(course.students.count,'student')%> enrolled</p>
	      </div>
	    </div>
	    <div class="extra content">
	      <div class="ui two buttons">
	        <% if @current_student.courses.exists?(course.id) %>	
	        	<% if controller.controller_name=="courses" && controller.action_name=="index" %>
			        <div class="ui grey button">        	
			        	<%= "Already Enrolled" %>
			        </div>
		         <% end %>
		         <% if controller.controller_name=="students" && controller.action_name=="show" %>
			        <div class="ui red button">        	
			        	<%=link_to "UnEnroll", unenroll_path(:course_id=>course.id), method: :delete, data: {confirm: "Are you sure to unenroll this course?"}  %>
			        </div>
		         <% end %>
	        <% else %>
	        	 <div class="ui green button">  
	        		<%= link_to( "Enroll", enroll_path(:course_id => course.id), method: :post) %>
	        	</div>
	        <% end %>
	        <div class="ui olive button"><%= link_to "Info", course_path(course)%></div>
	      </div>
	    </div>
	  </div>
</div>
</div>

app/views/courses/_form.html.erb
<%= form_for(@course, html:{class: "ui large form", role: "form"}) do |f|%>
  <div class="two fields">
    <div class="field">
      <label>Course Name</label>
     <%= f.text_field :name%>
    </div>
    <div class="field">
      <label>Course decription</label>
      <%= f.text_field :description%>
    </div>
  </div>
  <div ><%= f.submit(class: "ui submit red button") %></div>
<% end %>
    
    

app/views/courses/edit.html.erb
<%= render 'courses/form'%>

app/views/courses/index.html.erb
<div class="ui grid">
	<div class="sixteen wide column">
			<center>
				
			<p><h2>Current available courses Listing</h2></p>
				
			<%= link_to "Add a Course", new_course_path%>
				
			</center>
	</div>
	  	<%= render @courses%>
 </div>

app/views/courses/new.html.erb
<%= render 'courses/form'%>

app/views/courses/show.html.erb
<%= render 'courses/course', course: @course%>

app/views/layouts/_messages.html.erb
<div class="ui container">
	<% flash.each do |message_type, message_content|%>
		<div class="ui <%= message_type %> message">
	  		<i class="close icon"></i>
		  	<div class="header">
		    <%= message_content %> 
		  	</div>
		</div>
	<% end %>
</div>

app/views/layouts/_navigation.html.erb
<div class="ui red inverted menu">
	<div class="ui container">
	  <%= link_to "All Courses", courses_path, class: "item"%>
	  <a class="item">
	    Enrollments
	  </a>
	  <div class="ui dropdown item">
	      Account <i class="dropdown icon"></i>
	      <div class="menu">
	       	<% if logged_in?%> 
	       		<%= link_to "Log out", logout_path, method: :delete, class: "item "%>
	       		<%= link_to "My courses", student_path(@current_student),  class: "item "%>
	       	<% else %>
	       		<%= link_to "Log in", login_path, class: "item "%>
	        	<%= link_to "Sign up", new_student_path, class: "item "%>
	       	<% end %>    
	       	<% if logged_in? && session[:admin] &&  session[:admin] =='Y'%>
	       		<%= link_to "All students", students_path,  class: "item "%>
	       	<% end %>  
	      </div>
	    </div>
	  <div class="right menu ">
	  <p>
	    <h3 style="color:#fff">Tech University</h3>
	  </p>
	  </div>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UniversityApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>

  	<%= render 'layouts/navigation' %>
  	<%= render 'layouts/messages' %>
  	<div class="ui container">
    	<%= yield %>
    </div>
  </body>
</html>

app/views/pages/home.html.erb
This is the home page

app/views/students/_form.html.erb
<%= form_for(@student, html: {class: "ui form "}) do |f|%>
  <div class="four fields">
    <div class="field"></div>
    <div class="field">
      <label>First name</label>
      <%= f.text_field :firstname, placeholder: "First Name"%>
    </div>
    
    <div class="field">
      <label>Last name</label>      	
      <%= f.text_field :lastname, placeholder: "Last Name"%>
    </div>
    <div class="field"></div>
  </div>
  <div class="four fields">  
    <div class="field"></div>
  	<div class="field">
      <label>User name</label>
      <%= f.text_field :username, placeholder: "User Name"%>
    </div>
    
    <div class="field">
      <label>Email</label>
      <%= f.text_field :email, placeholder: "Email"%>
    </div>    
    <div class="field"></div>
    
  </div>
  <div class="four fields">
    <div class="field"></div>
	  <div class="six wide field">
	  </div>
    <div class="four wide field">
    	<div><%= f.button(@student.new_record?? "Sign up" : "Update", class: "ui fluid large  submit button red") %></div>
    </div>
    <div class="six wide field">
	  </div>
    <div class="field"></div>
  </div>
<% end %>

app/views/students/_student.html.erb
<div class="four wide column">
	<div class="ui cards">
	  <div class="card">
	    <div class="content">
	      <div class="header">
	        <%= student.firstname %>
	        <%= student.lastname %>
 	      </div>
 	      <div class="meta">
	        <%= student.username %>
 	      </div>
	      <div class="description">
	        <%= student.email %>
	      </div>
	    </div>
	    <div class="extra content">
	      <div class="ui three buttons">
	        <%= link_to "Edit", edit_student_path(student), class: "ui primary button"%>
	        <% if !(@current_student== student && session[:admin] && session[:admin]=='Y')%>
	        	<%= link_to "Info", student_path(student), class: "ui green button"%>
	        	<%= link_to "Remove", student_path(student), method: :delete, class: "ui red button", data: {confirm: "Are you sure to remove this student account?"}%>       
	      	<% end %>
	      </div>
	    </div>
	  </div>
	</div>
</div>

app/views/students/edit.html.erb
 <div class="ui segment">
	<%= render 'students/form'%>
</div>

app/views/students/index.html.erb
<div class="ui grid">
	<div class="sixteen wide column">
		<h2>
			<center>Course Listing</center>
		</2>
	</div>
	  	<%= render @students%>
 </div>

app/views/students/new.html.erb
 <div class="ui segment">
	<%= render 'students/form'%>
</div>

app/views/students/show.html.erb
<div class="ui grid">
	<div class="six wide column">
	</div>
	<div class="four wide column">
		<center><%= render "/students/student", student: @student%></center>
	</div>
	<div class="sixteen wide column">
		<h2>	
			<center>
				Course Listing for <%= @student.firstname%> <%= @student.lastname%>
			</center>
		</2>	
	</div>
	<% @my_courses.each do |course|%>
		<%= render 'courses/course', course: course%>
	<% end %>
</div>